# Generated by Django 2.1.7 on 2019-03-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown Album', max_length=100)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField(blank=True)),
                ('rate', models.FloatField(default=0, null=True)),
                ('likes', models.PositiveSmallIntegerField(default=0, null=True)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(upload_to='albums/%Y-%m-%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Various Artists', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('album', models.ManyToManyField(to='app_music.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('music_file', models.FileField(upload_to='albums/%y-%m-%d/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_music.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_music.Artist'),
        ),
    ]
