# Generated by Django 2.1.7 on 2019-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0003_auto_20190330_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='app_music.Tag'),
        ),
    ]
